spring:
    main.banner-mode: off
    application:
        name: mongo-db-reactive-app-example

server:
    port: 8080
    shutdown: graceful

management:
    server:
        port: 8090
    endpoints:
        enabled-by-default: false
        web:
            exposure.include: health,info,prometheus
    endpoint:
        health:
            enabled: true
            probes.enabled: true
            group:
                readiness:
                    include: readinessState,mongo
                    additional-path: server:/readyz # In order to collect probes from application main port
        info:
            enabled: true
        prometheus:
            enabled: true
    info:
        env.enabled: true
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    metrics:
        distribution:
            percentiles-histogram:
                http.server.requests: true
            minimum-expected-value:
                http.server.requests: 10ms
            maximum-expected-value:
                http.server.requests: 10s
            slo:
                http.server.requests: 1s
    prometheus:
        metrics:
            export:
                enabled: true
