spring:
    main.banner-mode: off
    application:
        name: spring-boot-2-bom-example

server:
    port: 8080
    servlet:
        context-path: /api
    tomcat:
        threads:
            max: 10
            min-spare: 5 # actuator port uses the same configuration
    shutdown: graceful

management:
    server:
        port: 8090
    endpoints:
        enabled-by-default: false
        web:
            exposure.include: health,info,prometheus,openapi,swaggerui
    endpoint:
        health:
            enabled: true
            probes.enabled: true
            group:
                readiness:
                    include: readinessState
                    additional-path: server:/readyz # In order to collect probes from application main port
        info:
            enabled: true
        prometheus:
            enabled: true
    info:
        env.enabled: true
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    metrics:
        distribution:
            percentiles-histogram:
                http.server.requests: true
            minimum-expected-value:
                http.server.requests: 10ms
            maximum-expected-value:
                http.server.requests: 10s
            slo:
                http.server.requests: 1s
        export:
            prometheus.enabled: true

springdoc:
    show-actuator: true
    use-management-port: true
